name: StopIt
description: A handy voice controlled stopwatch. 

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_picker: ^2.0.1
  permission_handler: ^10.4.3
  path_provider: ^2.0.15
  lecle_downloads_path_provider: ^0.0.2+8
  file_picker: ^5.2.6
  porcupine_flutter: ^2.2.0
  path: ^1.8.0
  google_fonts: ^5.1.0
  get_storage: ^2.1.1
  beep_player: ^0.0.1
  flutter_launcher_icons: ^0.13.1
  wakelock: ^0.6.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/AppIcon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/sounds/
    - assets/Logo.png
    - assets/models/
    - assets/keywords/android/
    - assets/keywords/ios/
    - assets/test_resources/
    - assets/keywords/android/StopIt_android.ppn
    - assets/test_resources/audio_samples/
    - assets/test_resources/keyword_files/
    - assets/test_resources/model_files/


